apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandwichmaker
spec:
  selector:
    matchLabels:
      app: sandwichmaker
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: sandwichmaker
    spec:
      containers:
      - name: sandwichmaker
        image: myrepository.azurecr.io/sandwichmaker:lab05
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: SANDWICHMAKER__URL
          value: http://sandwichmaker
        - name: BREADSERVICE__URL
          value: http://breadservice
        - name: CHEESESERVICE__URL
          value: http://cheeseservice
        - name: MEATSERVICE__URL
          value: http://meatservice
        - name: LETTUCESERVICE__URL
          value: http://lettuceservice
      imagePullSecrets:
      - name: acr-auth