version: '3.4'

services:
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    depends_on:
      - sandwichmaker
    environment: 
      - SANDWICHMAKER__URL=http://sandwichmaker

  sandwichmaker:
    image: ${DOCKER_REGISTRY-}sandwichmaker
    build:
      context: .
      dockerfile: SandwichMaker/Dockerfile
    depends_on:
      - breadservice
      - cheeseservice
      - meatservice
      - lettuceservice
    environment: 
      - BREADSERVICE__URL=http://breadservice
      - CHEESESERVICE__URL=http://cheeseservice
      - MEATSERVICE__URL=http://meatservice
      - LETTUCESERVICE__URL=http://lettuceservice

  breadservice:
    image: ${DOCKER_REGISTRY-}breadservice
    build:
      context: .
      dockerfile: BreadService/Dockerfile

  cheeseservice:
    image: ${DOCKER_REGISTRY-}cheeseservice
    build:
      context: .
      dockerfile: CheeseService/Dockerfile

  meatservice:
    image: ${DOCKER_REGISTRY-}meatservice
    build:
      context: .
      dockerfile: MeatService/Dockerfile

  lettuceservice:
    image: ${DOCKER_REGISTRY-}lettuceservice
    build:
      context: .
      dockerfile: LettuceService/Dockerfile
